# cuda
cuda_index: 0
seed: 42

# path
annotation_dir: ../data/dataset/annotation
json_path: ../data/dataset/jsons
preprocessed_dir: ../data/preprocessed
resume_from: ./exps/exp17/outputs/lang-zh_epoch05_score0.3365.pth.tar
save_limits: 1
bert-en:
  bert_path: roberta-large
  cls: '<s>'
  sep: '</s>'
  unk: '<unk>'
  pad: '<pad>'

bert-zh:
  bert_path: hfl/chinese-macbert-large
  cls: '[CLS]'
  sep: '[SEP]'
  unk: '[UNK]'
  pad: '[PAD]'

unkown_tokens: '🍔—🐛🙉🙄🔨🏆🆔👌👀🥺冖🌚🙈😭🍎😅💩尛硌糇💰🐴🙊💯⭐🐶🐟🙏😄🏻📶🐮🍺❌🤔🐍🐸🙃🤣🏆😂🌚'
max_length: 512

# parameter
epoch_size: 20
batch_size: 1
lr: 1e-5
patience: 10
max_grad_norm: 5.0
scheduler: linear_with_warmup #cosine_with_warmup # cosine_with_warmup
warmup_proportion: 0.1
gradient_accumulation_steps: 1
adam_epsilon: 1e-8
warmup_steps: 0
weight_decay: 1e-4
enable_fp16: False

# dict
bio_mode: 'OBIES'
asp_type: 'Aspect'
tgt_type: 'Target'
opi_type: 'Opinion'

polarity_dict:
  O: 0
  pos: 1
  neg: 2
  other: 3


# You can set this value to 'False' to save GPU memory, but the performance may decrease.
use_rope: True

loss_weight:
  ent: 1
  rel: 3
  pol: 3
